### ISSUE TITLE
NoMethodError: undefined method `wday' for nil:NilClass

### ISSUE THREAD

**Issue by aprotsyk** [zendesk/biz#110] opened 2017-07-14 02:25 UTC
Hi guys,
I have next simple configuration:
```
biz = Biz::Schedule.new do |config|
  config.hours = {
          mon: {'09:00' => '17:00'},
          tue: {'08:00' => '17:00'},
          wed: {'09:00' => '17:00'},
          thu: {'09:00' => '12:00', '13:00' => '17:00'},
          fri: {'08:00' => '14:00'},
          sat: {'10:00' => '14:00'}
  }
  config.time_zone = 'Pacific/Auckland'
end
```
call next statement

`biz.periods.after(Time.current).timeline.until(Time.current + 1.week).to_a`

throw error:

```
NoMethodError: undefined method `wday' for nil:NilClass
from /Users/aprotsyk/.rvm/gems/ruby-2.3.1@panacea2/gems/biz-1.7.0/lib/biz/time.rb:94:in `during_week'
```
I can't figure out what I'm doing wrong
Thanks

**Comment by craiglittle** [comment] 2017-07-14 18:16
That's no good, @aprotsyk! I'll take a look.

**Comment by craiglittle** [comment] 2017-07-14 22:40
I'm not able to reproduce this, @aprotsyk.

Are you sure your configuration is actually like what is listed above? If it's malformed in some way, you might be getting that error.

**Comment by aprotsyk** [comment] 2017-07-15 00:02
I began disabling gems one by one and detected that this bug reproduced with gem 'ruby-units'. so it's not gem bug, looks like "ruby-units" doing some core overrides. thanks @craiglittle  for your quick response.

**Comment by craiglittle** [comment] 2017-07-15 00:19
Sweet, glad you figured it out! :skull: to monkey patches. 😀 

I'll go ahead and close this issue. Let me know if you run into any other issues, though!

**Closed by craiglittle** 2017-07-15 00:19 UTC
